services:
  backend:
    build:
      context: ./COMP_2432project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
